services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    hostname: ctr-gateway
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TS_AUTHKEY: "tskey-auth-kUjR7CvABg11CNTRL-YHJLN71GVfTSayQ2VNNCfT6tefx44sge"
      #TS_ACCEPT_DNS: "true"
      #TS_ROUTES: "192.168.0.0/24"
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun