services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - tailscale-var-lib:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    command: tailscaled

  tailscale-up:
    image: tailscale/tailscale
    depends_on:
      - tailscale
    network_mode: service:tailscale
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
    volumes:
      - tailscale-var-lib:/var/lib/tailscale
    command: tailscale up --authkey=${TS_AUTHKEY} --hostname=tailscale-docker --advertise-tags=tag:docker

volumes:
  tailscale-var-lib:
